# -*- coding: utf-8 -*-
"""Readme.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYewPcrWl5V_q7OYJstW8pmTeK9P0Y75

# 📸 Photography Performance Dashboard with Power BI

## Overview
This Power BI dashboard analyzes Instagram post performance for the handle **@yellowbumblebeegt**. It provides key performance insights that help photographers, creators, and digital marketers understand **what content works best**, when to post, and how different post types (Reels, Images, Carousels) perform over time.

Whether you're growing a content strategy or reviewing analytics from brand collaborations, this dashboard offers an intuitive and data-driven view of Instagram engagement.


## 🎯 Objectives
- Track overall content performance metrics (Posts, Reach, Engagement, Followers)
- Identify the **best days and time slots to post**
- Compare post types like **IG Reels, Images, and Carousels**
- Highlight **top-performing posts** by reach and engagement
- Offer interactive filters and clean visuals for better storytelling


## 📊 Key KPIs Tracked
- **Total Posts** (by Post Type)
- **Total Reach**
- **Total Engagement** (Likes + Comments + Shares + Saves)
- **Average Engagement Rate (%)**
- **Total Follows Gained**
- **Top Performing Post** (by Engagement Rate)
- **Best Day and Time Slot to Post**


## 📈 Dashboard Sections
### 1. KPI Cards (Top Summary)
- Displays total posts, reach, engagement, followers, and average engagement rate in an easy-to-read card layout.

### 2. Engagement Over Time
- A line chart showing how engagement has changed over time.

### 3. Avg Engagement Rate by Post Type
- Bar chart comparing performance of IG Reels, Images, and Carousels.

### 4. Best Day & Time to Post
- A heatmap matrix showing the engagement rate by **day of the week** and **hour of the day**, color-coded using conditional formatting.

### 5. Top Performing Posts
- A clickable table of the best-performing posts with caption, reach, engagement, and hyperlinks to the actual post.

### 6. Filters / Slicers
- Interactive slicers for:
  - Post Type (Reel, Image, Carousel)
  - Date Range
  - Day of the Week
"""